"""
Graph Foundation: Nodes, Relationships, and Base Types

This module defines the core graph structure used throughout the system.
All nodes inherit from BaseSemanticaNode and use the generic Relationship model.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


class RelationshipType(str, Enum):
    """
    Node relationship types.
    Extending this Enum keeps the rest of the schema unchanged (Future-Proof).
    """

    # [Code Structure]
    CALLS = "calls"  # function -> function
    CALLED_BY = "called_by"  # function <- function
    IMPORTS = "imports"  # module/file import
    DEFINES = "defines"  # file/module -> symbol
    INHERITS = "inherits"  # class -> class
    IMPLEMENTS = "implements"  # class -> interface
    DEPENDS_ON = "depends_on"  # project -> project

    # [Name Resolution - v2 Extension]
    REFERS_TO = "refers_to"  # variable/function reference
    OVERRIDES = "overrides"  # method override
    SHADOWS = "shadows"  # name shadowing

    # [Cross-Asset]
    TESTS = "tests"  # test code ↔ target code
    DOCUMENTS = "documents"  # documentation ↔ code
    CONFIGURES = "configures"  # config ↔ code

    # [Security / Git]
    RELATED_CVE = "related_cve"  # vulnerability DB integration
    TOUCHES = "touches"  # PR/Commit changes to chunk/symbol
    GENERATED_FROM = "generated_from"  # generated by external tool
    ORIGIN_COMMIT = "origin_commit"  # origin commit of this node


class Relationship(BaseModel):
    """
    Generic graph edge with flexible metadata.
    """

    target_id: str
    type: RelationshipType
    metadata: dict[str, Any] = Field(default_factory=dict)


class BaseSemanticaNode(BaseModel):
    """
    [Safety Net] Common ancestor for all nodes.
    - relationships: graph connections
    - attrs: schema-less extension pocket (no schema migration needed)
    - importance_score: RepoMap / importance calculation result (PageRank + Git + Runtime)
    - token_estimate: Token count estimate for this node and children (skeleton-based)
    - schema_version: Schema version for A/B testing and experiments
    """

    node_id: str
    node_type: str
    schema_version: str = "v2.0"

    relationships: list[Relationship] = Field(default_factory=list)
    attrs: dict[str, Any] = Field(default_factory=dict)

    # RepoMap / Importance calculation fields
    importance_score: Optional[float] = None
    token_estimate: Optional[int] = None

    def add_attr(self, key: str, value: Any) -> None:
        """Add custom attribute to the attrs dictionary."""
        self.attrs[key] = value

    def add_relationship(
        self,
        target_id: str,
        rel_type: RelationshipType,
        metadata: Optional[dict[str, Any]] = None,
    ) -> None:
        """Add a relationship to another node."""
        self.relationships.append(
            Relationship(
                target_id=target_id,
                type=rel_type,
                metadata=metadata or {},
            )
        )
