"""
Agent Roles

토론에 참여하는 에이전트 역할 정의.
"""

import logging
from collections.abc import Callable

from .debate_models import AgentRole, Position

logger = logging.getLogger(__name__)


class DebateAgent:
    """토론 에이전트"""

    def __init__(
        self,
        role: AgentRole,
        agent_id: str,
        generate_fn: Callable[[str], str],
    ):
        self.role = role
        self.agent_id = agent_id
        self.generate_fn = generate_fn

    async def generate_position(self, problem: str, previous_positions: list[Position] | None = None) -> Position:
        """
        포지션 생성

        Args:
            problem: 문제
            previous_positions: 이전 포지션들

        Returns:
            새로운 포지션
        """
        # 프롬프트 구성
        prompt = self._build_prompt(problem, previous_positions)

        try:
            # LLM으로 생성
            response = self.generate_fn(prompt)

            # 포지션 파싱
            position = self._parse_response(response)

            logger.debug(f"Agent {self.agent_id} ({self.role}) generated position: {position.content[:50]}...")

            return position

        except Exception as e:
            logger.warning(f"Failed to generate position: {e}")
            # 기본 포지션 반환
            return Position(
                agent_role=self.role,
                content="No position",
                reasoning="Failed to generate",
                confidence=0.0,
            )

    def _build_prompt(self, problem: str, previous_positions: list[Position] | None) -> str:
        """프롬프트 구성"""
        prompt_parts = [f"Problem: {problem}\n"]

        if self.role == AgentRole.PROPOSER:
            prompt_parts.append("Your role: Propose a solution to this problem.")

        elif self.role == AgentRole.CRITIC:
            prompt_parts.append("Your role: Critically evaluate the proposed solutions.")
            if previous_positions:
                prompt_parts.append("\nPrevious proposals:")
                for pos in previous_positions:
                    if pos.agent_role == AgentRole.PROPOSER:
                        prompt_parts.append(f"- {pos.content}")

        elif self.role == AgentRole.JUDGE:
            prompt_parts.append("Your role: Judge the debate and make the final decision.")
            if previous_positions:
                prompt_parts.append("\nAll positions:")
                for pos in previous_positions:
                    prompt_parts.append(f"- [{pos.agent_role}] {pos.content}")

        return "\n".join(prompt_parts)

    def _parse_response(self, response: str) -> Position:
        """응답 파싱 (간단 버전)"""
        return Position(
            agent_role=self.role,
            content=response,
            reasoning=f"Generated by {self.role}",
            confidence=0.8,  # 기본값
        )

    def generate_position_sync(self, problem: str, previous_positions: list[Position] | None = None) -> Position:
        """동기 버전"""
        import asyncio

        return asyncio.run(self.generate_position(problem, previous_positions))
