# Balanced Preset Configuration
# Use for: Daily builds, code review, general development
# Performance: 10-60s latency, 1-5GB memory

version: 1
preset: balanced

stages:
  # All basic stages enabled
  parsing: true
  chunking: true
  cross_file: true
  cfg: true
  dfg: true
  type_inference: true

  # Moderate analyses
  taint: true
  pta: false  # Optional, enable for higher precision
  clone: true
  repomap: true

overrides:
  # Balanced taint analysis
  taint:
    max_depth: 20
    max_paths: 500
    use_points_to: false  # Can enable with PTA
    field_sensitive: false
    use_ssa: false
    detect_sanitizers: true
    enable_interprocedural: true
    worklist_max_iterations: 100

  # Flow-insensitive PTA (if enabled)
  pta:
    mode: flow_insensitive
    max_iterations: 100
    field_sensitive: false
    context_sensitive: 1
    enable_cycle_elimination: true
    use_cache: true

  # Clone detection (Type 1-3)
  clone:
    min_tokens: 50
    min_lines: 6
    type1:
      enable_exact_matching: true
    type2:
      enable_normalization: true
    type3:
      max_gap_ratio: 0.3
      enable_gapped_detection: true
    type4: null  # Disabled (expensive)

  # Standard chunking
  chunking:
    max_chunk_tokens: 512
    overlap_tokens: 64
    enable_semantic_split: true
    min_chunk_tokens: 50

  # Lexical search with fuzzy matching
  lexical:
    enable_fuzzy: true
    fuzzy_distance: 2
    enable_ngram: true
    ngram_size: 3
    boost_exact_match: 2.0

  # PageRank for RepoMap
  pagerank:
    damping_factor: 0.85
    max_iterations: 100
    convergence_threshold: 0.000001
    enable_personalization: false

  # Balanced parallelism
  parallel:
    workers: 0  # 0 = num_cpus
    batch_size: 100
    enable_rayon: true

  # Balanced caching
  cache:
    enable_background_l2_writes: true
    l0:
      max_entries: 10000
      enable_bloom_filter: true
      expected_items: 100000
      false_positive_rate: 0.01
    l1:
      max_entries: 1000
      max_bytes: 536870912  # 512MB
      ttl_seconds: 3600  # 1 hour
    l2:
      cache_dir: ".cache/codegraph"
      max_disk_bytes: 10737418240  # 10GB
      enable_compression: true
      enable_mmap: true
